In [1]:
import pandas as pd

meta_data = pd.read_csv(r"C:\Users\koush\Desktop\GenAi project folder\meta_index.csv")
print(meta_data)

                                                file      label  category  \
0                 genai_chatgpt_audio_01_packets.csv      genai       NaN
1                 genai_chatgpt_audio_02_packets.csv      genai       NaN
2                  genai_chatgpt_text_01_packets.csv      genai       NaN
3                  genai_chatgpt_text_02_packets.csv      genai       NaN
4                  genai_chatgpt_text_03_packets.csv      genai       NaN
5                  genai_chatgpt_text_04_packets.csv      genai       NaN
6                  genai_chatgpt_text_05_packets.csv      genai       NaN
7                  genai_chatgpt_text_06_packets.csv      genai       NaN
8                 genai_chatgpt_video_01_packets.csv      genai       NaN
9                 genai_chatgpt_video_02_packets.csv      genai       NaN
10                genai_chatgpt_video_03_packets.csv      genai       NaN
11                genai_chatgpt_video_04_packets.csv      genai       NaN
12                 genai_gemini_audio_01_packets.csv      genai       NaN
13                 genai_gemini_audio_02_packets.csv      genai       NaN
14                 genai_gemini_audio_03_packets.csv      genai       NaN
15                  genai_gemini_text_01_packets.csv      genai       NaN
16                  genai_gemini_text_02_packets.csv      genai       NaN
17                  genai_gemini_text_03_packets.csv      genai       NaN
18                  genai_gemini_text_04_packets.csv      genai       NaN
19                  genai_gemini_text_05_packets.csv      genai       NaN
20                    genai_grok_text_01_packets.csv      genai       NaN
21             genai_perplexity_audio_01_packets.csv      genai       NaN
22              genai_perplexity_text_01_packets.csv      genai       NaN
23          non_genai_browsing_chrome_01_packets.csv  non_genai  browsing
24          non_genai_browsing_chrome_02_packets.csv  non_genai  browsing
25          non_genai_browsing_chrome_03_packets.csv  non_genai  browsing
26          non_genai_browsing_chrome_04_packets.csv  non_genai  browsing
27            non_genai_stream_disney_01_packets.csv  non_genai    stream
28            non_genai_stream_disney_02_packets.csv  non_genai    stream
29            non_genai_stream_disney_03_packets.csv  non_genai    stream
30          non_genai_browsing_google_01_packets.csv  non_genai  browsing
31          non_genai_browsing_google_02_packets.csv  non_genai  browsing
32          non_genai_browsing_google_03_packets.csv  non_genai  browsing
33  non_genai_audio_calling_instagram_01_packets.csv  non_genai   calling
34  non_genai_video_calling_instagram_01_packets.csv  non_genai   calling
35          non_genai_browsing_safari_01_packets.csv  non_genai  browsing
36          non_genai_browsing_safari_02_packets.csv  non_genai  browsing
37          non_genai_browsing_safari_03_packets.csv  non_genai  browsing
38            non_genai_stream_twitch_01_packets.csv  non_genai    stream
39            non_genai_stream_twitch_02_packets.csv  non_genai    stream
40            non_genai_stream_twitch_03_packets.csv  non_genai    stream
41   non_genai_audio_calling_whatsapp_01_packets.csv  non_genai   calling
42   non_genai_video_calling_whatsapp_01_packets.csv  non_genai   calling
43           non_genai_stream_youtube_01_packets.csv  non_genai    stream
44           non_genai_stream_youtube_02_packets.csv  non_genai    stream
45           non_genai_stream_youtube_03_packets.csv  non_genai    stream
46       non_genai_audio_calling_zoom_01_packets.csv  non_genai   calling
47       non_genai_video_calling_zoom_01_packets.csv  non_genai   calling

           app   mode  run_id
0      chatgpt  audio       1
1      chatgpt  audio       2
2      chatgpt   text       1
3      chatgpt   text       2
4      chatgpt   text       3
5      chatgpt   text       4
6      chatgpt   text       5
7      chatgpt   text       6
8      chatgpt  video       1
9      chatgpt  video       2
10     chatgpt  video       3
11     chatgpt  video       4
12      gemini  audio       1
13      gemini  audio       2
14      gemini  audio       3
15      gemini   text       1
16      gemini   text       2
17      gemini   text       3
18      gemini   text       4
19      gemini   text       5
20        grok   text       1
21  perplexity  audio       1
22  perplexity   text       1
23      chrome    NaN       1
24      chrome    NaN       2
25      chrome    NaN       3
26      chrome    NaN       4
27      disney    NaN       1
28      disney    NaN       2
29      disney    NaN       3
30      google    NaN       1
31      google    NaN       2
32      google    NaN       3
33   instagram  audio       1
34   instagram  video       1
35      safari    NaN       1
36      safari    NaN       2
37      safari    NaN       3
38      twitch    NaN       1
39      twitch    NaN       2
40      twitch    NaN       3
41    whatsapp  audio       1
42    whatsapp  video       1
43     youtube    NaN       1
44     youtube    NaN       2
45     youtube    NaN       3
46        zoom  audio       1
47        zoom  video       1

In [2]:
meta = meta_data.copy()
print(meta.columns)
print('rows:',len(meta))

Index(['file', 'label', 'category', 'app', 'mode', 'run_id'], dtype='object')
rows: 48

In [3]:
import os
folder_path = r"C:\Users\koush\Desktop\GenAi project folder\CSV"
one_file= meta["file"].iloc[0]
file_path = os.path.join(folder_path,one_file)
df = pd.read_csv(file_path)
print(df)

         No.        Time          Source     Destination Protocol  Length  \
0          1    0.000000  192.168.137.80   192.168.137.1      DNS      74
1          2    0.001659   192.168.137.1  192.168.137.80      DNS     120
2          3    0.081983  192.168.137.80   192.168.137.1      DNS      78
3          4    0.082496  192.168.137.80   192.168.137.1      DNS      74
4          5    0.082806  192.168.137.80    104.18.32.47      TCP      74
...      ...         ...             ...             ...      ...     ...
36052  36053  332.351875  192.168.137.80    4.151.200.38      SSL     180
36053  36054  332.369503  192.168.137.80    4.151.200.38      SSL     179
36054  36055  332.388743  192.168.137.80    4.151.200.38      SSL     173
36055  36056  332.413717  192.168.137.80    4.151.200.38      SSL     170
36056  36057  332.461600    4.151.200.38  192.168.137.80      TCP      66

                                                    Info
0                 Standard query 0xa35b A ab.chatgpt.com
1      Standard query response 0xa35b A ab.chatgpt.co...
2             Standard query 0x504a A api.revenuecat.com
3                 Standard query 0xf6e6 A ab.chatgpt.com
4      51476  >  443 [SYN] Seq=0 Win=65535 Len=0 MSS=...
...                                                  ...
36052                                  Continuation Data
36053                                  Continuation Data
36054                                  Continuation Data
36055                                  Continuation Data
36056  443  >  37117 [ACK] Seq=1849 Ack=53617 Win=814...

[36057 rows x 7 columns]

In [4]:
df["Time"] = pd.to_numeric(df["Time"], errors="coerce")
df = df.dropna(subset=["Time"])

In [5]:
total_packets=len(df)
duration_sec=df["Time"].max()-df["Time"].min()

In [6]:
print("File:", one_file)
print("Total packets:", total_packets)
print("Duration (sec):", duration_sec)
print("Time sorted?", df["Time"].is_monotonic_increasing)

File: genai_chatgpt_audio_01_packets.csv
Total packets: 36057
Duration (sec): 332.4616
Time sorted? True

In [7]:
df["Source"].value_counts().head(10)

Source
16.15.191.220      14814
192.168.137.80     12459
104.21.86.57        2024
4.151.200.38        1532
104.18.9.181        1155
172.64.155.214       920
172.203.39.49        629
172.214.226.198      497
172.66.147.128       482
104.18.32.47         262
Name: count, dtype: int64

In [8]:
df["Destination"].value_counts().head(10)

Destination
192.168.137.80     23451
16.15.191.220       3868
4.151.200.38        3456
172.214.226.198      985
172.64.155.214       858
172.203.39.49        764
104.21.86.57         701
104.18.9.181         565
104.18.32.47         184
172.66.147.128       180
Name: count, dtype: int64

In [9]:
import ipaddress
import numpy as np

def is_private_ip(ip):
    try:
        return ipaddress.ip_address(ip).is_private
    except:
        return False

In [10]:
src_counts = df["Source"].value_counts()
dst_counts = df["Destination"].value_counts()

common_ips = set(src_counts.index).intersection(set(dst_counts.index))
private_common = [ip for ip in common_ips if is_private_ip(ip)]

In [11]:
ip_scores = {
    ip: src_counts.get(ip, 0) + dst_counts.get(ip, 0)
    for ip in private_common
}

MY_IP = max(ip_scores, key=ip_scores.get)
print("Detected client IP:", MY_IP)

Detected client IP: 192.168.137.80

In [12]:
df["direction"] = np.where(df["Source"] == MY_IP, 1, -1)
# +1 = UL, -1 = DL

In [13]:
print(df)

         No.        Time          Source     Destination Protocol  Length  \
0          1    0.000000  192.168.137.80   192.168.137.1      DNS      74
1          2    0.001659   192.168.137.1  192.168.137.80      DNS     120
2          3    0.081983  192.168.137.80   192.168.137.1      DNS      78
3          4    0.082496  192.168.137.80   192.168.137.1      DNS      74
4          5    0.082806  192.168.137.80    104.18.32.47      TCP      74
...      ...         ...             ...             ...      ...     ...
36052  36053  332.351875  192.168.137.80    4.151.200.38      SSL     180
36053  36054  332.369503  192.168.137.80    4.151.200.38      SSL     179
36054  36055  332.388743  192.168.137.80    4.151.200.38      SSL     173
36055  36056  332.413717  192.168.137.80    4.151.200.38      SSL     170
36056  36057  332.461600    4.151.200.38  192.168.137.80      TCP      66

                                                    Info  direction
0                 Standard query 0xa35b A ab.chatgpt.com          1
1      Standard query response 0xa35b A ab.chatgpt.co...         -1
2             Standard query 0x504a A api.revenuecat.com          1
3                 Standard query 0xf6e6 A ab.chatgpt.com          1
4      51476  >  443 [SYN] Seq=0 Win=65535 Len=0 MSS=...          1
...                                                  ...        ...
36052                                  Continuation Data          1
36053                                  Continuation Data          1
36054                                  Continuation Data          1
36055                                  Continuation Data          1
36056  443  >  37117 [ACK] Seq=1849 Ack=53617 Win=814...         -1

[36057 rows x 8 columns]

In [14]:
print(df.tail(10))

         No.        Time          Source     Destination Protocol  Length  \
36047  36048  332.148817  192.168.137.80    4.151.200.38      SSL     157
36048  36049  332.216222    4.151.200.38  192.168.137.80      TCP      66
36049  36050  332.216265    4.151.200.38  192.168.137.80      TCP      66
36050  36051  332.316598  192.168.137.80    4.151.200.38      SSL     791
36051  36052  332.329231  192.168.137.80    4.151.200.38      SSL     180
36052  36053  332.351875  192.168.137.80    4.151.200.38      SSL     180
36053  36054  332.369503  192.168.137.80    4.151.200.38      SSL     179
36054  36055  332.388743  192.168.137.80    4.151.200.38      SSL     173
36055  36056  332.413717  192.168.137.80    4.151.200.38      SSL     170
36056  36057  332.461600    4.151.200.38  192.168.137.80      TCP      66

                                                    Info  direction
36047                                  Continuation Data          1
36048  443  >  37117 [ACK] Seq=1849 Ack=51987 Win=814...         -1
36049  443  >  37117 [ACK] Seq=1849 Ack=52340 Win=814...         -1
36050                                  Continuation Data          1
36051                                  Continuation Data          1
36052                                  Continuation Data          1
36053                                  Continuation Data          1
36054                                  Continuation Data          1
36055                                  Continuation Data          1
36056  443  >  37117 [ACK] Seq=1849 Ack=53617 Win=814...         -1

In [15]:
df = df.sort_values("Time").reset_index(drop=True)

In [16]:
print(df)

         No.        Time          Source     Destination Protocol  Length  \
0          1    0.000000  192.168.137.80   192.168.137.1      DNS      74
1          2    0.001659   192.168.137.1  192.168.137.80      DNS     120
2          3    0.081983  192.168.137.80   192.168.137.1      DNS      78
3          4    0.082496  192.168.137.80   192.168.137.1      DNS      74
4          5    0.082806  192.168.137.80    104.18.32.47      TCP      74
...      ...         ...             ...             ...      ...     ...
36052  36053  332.351875  192.168.137.80    4.151.200.38      SSL     180
36053  36054  332.369503  192.168.137.80    4.151.200.38      SSL     179
36054  36055  332.388743  192.168.137.80    4.151.200.38      SSL     173
36055  36056  332.413717  192.168.137.80    4.151.200.38      SSL     170
36056  36057  332.461600    4.151.200.38  192.168.137.80      TCP      66

                                                    Info  direction
0                 Standard query 0xa35b A ab.chatgpt.com          1
1      Standard query response 0xa35b A ab.chatgpt.co...         -1
2             Standard query 0x504a A api.revenuecat.com          1
3                 Standard query 0xf6e6 A ab.chatgpt.com          1
4      51476  >  443 [SYN] Seq=0 Win=65535 Len=0 MSS=...          1
...                                                  ...        ...
36052                                  Continuation Data          1
36053                                  Continuation Data          1
36054                                  Continuation Data          1
36055                                  Continuation Data          1
36056  443  >  37117 [ACK] Seq=1849 Ack=53617 Win=814...         -1

[36057 rows x 8 columns]

In [17]:
df["iat"] = df["Time"].diff().fillna(0)

In [18]:
df[["Time", "Length", "direction", "iat"]].head()

       Time  Length  direction       iat
0  0.000000      74          1  0.000000
1  0.001659     120         -1  0.001659
2  0.081983      78          1  0.080324
3  0.082496      74          1  0.000513
4  0.082806      74          1  0.000310

In [19]:
print(df["direction"].value_counts())
print("IAT mean:", df["iat"].mean())
print("IAT max:", df["iat"].max())

direction
-1    23598
 1    12459
Name: count, dtype: int64
IAT mean: 0.009220445405885125
IAT max: 5.9439649999999915

In [20]:
import numpy as np

def pct(arr, p):
    return np.percentile(arr, p) if len(arr) > 0 else 0

ul = df[df["direction"] == 1]
dl = df[df["direction"] == -1]

duration_sec = df["Time"].max() - df["Time"].min()
total_packets = len(df)
total_bytes = df["Length"].sum()

ul_packets = len(ul)
dl_packets = len(dl)

ul_bytes = ul["Length"].sum()
dl_bytes = dl["Length"].sum()

dl_ul_byte_ratio = dl_bytes / ul_bytes if ul_bytes > 0 else 0
dl_ul_packet_ratio = dl_packets / ul_packets if ul_packets > 0 else 0

# packet sizes
pkt_size_mean = df["Length"].mean()
pkt_size_std = df["Length"].std()
pkt_size_p95 = pct(df["Length"], 95)

ul_pkt_size_mean = ul["Length"].mean()
ul_pkt_size_std = ul["Length"].std()

dl_pkt_size_mean = dl["Length"].mean()
dl_pkt_size_std = dl["Length"].std()
dl_pkt_size_p95 = pct(dl["Length"], 95)

# iat
iat_mean = df["iat"].mean()
iat_std = df["iat"].std()
iat_max = df["iat"].max()

ul_iat_mean = ul["iat"].mean()
ul_iat_std = ul["iat"].std()

dl_iat_mean = dl["iat"].mean()
dl_iat_std = dl["iat"].std()

# Unique destination count
unique_dst_ips = df["Destination"].nunique()

# throughput
bytes_per_second = total_bytes / duration_sec if duration_sec > 0 else 0

features = {
    "duration_sec": duration_sec,
    "total_packets": total_packets,
    "ul_packets": ul_packets,
    "dl_packets": dl_packets,
    "ul_bytes": ul_bytes,
    "dl_bytes": dl_bytes,
    "dl_ul_byte_ratio": dl_ul_byte_ratio,
    "dl_ul_packet_ratio": dl_ul_packet_ratio,
    "pkt_size_mean": pkt_size_mean,
    "pkt_size_std": pkt_size_std,
    "pkt_size_p95": pkt_size_p95,
    "ul_pkt_size_mean": ul_pkt_size_mean,
    "ul_pkt_size_std": ul_pkt_size_std,
    "dl_pkt_size_mean": dl_pkt_size_mean,
    "dl_pkt_size_std": dl_pkt_size_std,
    "dl_pkt_size_p95": dl_pkt_size_p95,
    "iat_mean": iat_mean,
    "iat_std": iat_std,
    "iat_max": iat_max,
    "ul_iat_mean": ul_iat_mean,
    "ul_iat_std": ul_iat_std,
    "dl_iat_mean": dl_iat_mean,
    "dl_iat_std": dl_iat_std,
    "unique_dst_ips": unique_dst_ips,
    "bytes_per_second": bytes_per_second,
}

features

{'duration_sec': np.float64(332.4616),
 'total_packets': 36057,
 'ul_packets': 12459,
 'dl_packets': 23598,
 'ul_bytes': np.int64(2068392),
 'dl_bytes': np.int64(24955917),
 'dl_ul_byte_ratio': np.float64(12.065371070860843),
 'dl_ul_packet_ratio': 1.8940524921743318,
 'pkt_size_mean': np.float64(749.4885597803478),
 'pkt_size_std': np.float64(565.5356112665996),
 'pkt_size_p95': np.float64(1304.0),
 'ul_pkt_size_mean': np.float64(166.01589212617384),
 'ul_pkt_size_std': np.float64(239.07230247226101),
 'dl_pkt_size_mean': np.float64(1057.5437325197051),
 'dl_pkt_size_std': np.float64(428.8024294641376),
 'dl_pkt_size_p95': np.float64(1304.0),
 'iat_mean': np.float64(0.009220445405885125),
 'iat_std': np.float64(0.06342033678050159),
 'iat_max': np.float64(5.9439649999999915),
 'ul_iat_mean': np.float64(0.01574809358696531),
 'ul_iat_std': np.float64(0.08855137065933193),
 'dl_iat_mean': np.float64(0.005774052970590693),
 'dl_iat_std': np.float64(0.04440258583998148),
 'unique_dst_ips': 39,
 'bytes_per_second': np.float64(81285.50485228971)}

In [ ]:
import os
import pandas as pd
import numpy as np
import ipaddress

META_PATH = r"C:\Users\koush\Desktop\GenAi project folder\meta_index.csv"
CSV_FOLDER = r"C:\Users\koush\Desktop\GenAi project folder\CSV"
OUT_PATH  = r"C:\Users\koush\Desktop\GenAi project folder\features_top25.csv"

# loading meta_data
meta = pd.read_csv(META_PATH)

def is_private_ip(ip: str) -> bool:
    try:
        return ipaddress.ip_address(ip).is_private
    except Exception:
        return False

def detect_client_ip(df: pd.DataFrame) -> str:
    """Pick the private IP that appears most in both Source and Destination."""
    src_counts = df["Source"].value_counts()
    dst_counts = df["Destination"].value_counts()

    common = set(src_counts.index).intersection(set(dst_counts.index))
    private_common = [ip for ip in common if is_private_ip(ip)]

    if not private_common:
        # pick most frequent private in Source+Destination combined
        all_ips = pd.concat([df["Source"], df["Destination"]], ignore_index=True)
        priv = all_ips[all_ips.apply(is_private_ip)]
        if priv.empty:
            raise ValueError("No private IP found to identify client.")
        return priv.value_counts().index[0]

    scores = {ip: src_counts.get(ip, 0) + dst_counts.get(ip, 0) for ip in private_common}
    return max(scores, key=scores.get)

def extract_features(df: pd.DataFrame) -> dict:
    df = df.copy()
    df["Time"] = pd.to_numeric(df["Time"], errors="coerce")
    df["Length"] = pd.to_numeric(df["Length"], errors="coerce")
    df = df.dropna(subset=["Time", "Length", "Source", "Destination"])
    if df.empty:
        raise ValueError("Empty df after cleaning Time/Length.")

    # detect client ip
    client_ip = detect_client_ip(df)
    
    df = df.sort_values("Time").reset_index(drop=True)
    df["direction"] = np.where(df["Source"] == client_ip, 1, -1)  # +1 UL, -1 DL

    df["iat"] = df["Time"].diff().fillna(0.0)

    ul = df[df["direction"] == 1]
    dl = df[df["direction"] == -1]

    duration_sec = float(df["Time"].max() - df["Time"].min())
    total_packets = int(len(df))
    total_bytes = float(df["Length"].sum())

    ul_packets = int(len(ul))
    dl_packets = int(len(dl))
    ul_bytes = float(ul["Length"].sum())
    dl_bytes = float(dl["Length"].sum())

    dl_ul_byte_ratio = (dl_bytes / ul_bytes) if ul_bytes > 0 else 0.0
    dl_ul_packet_ratio = (dl_packets / ul_packets) if ul_packets > 0 else 0.0

    # packet size
    pkt_size_mean = float(df["Length"].mean())
    pkt_size_std  = float(df["Length"].std(ddof=1)) if total_packets > 1 else 0.0
    pkt_size_p95  = float(np.percentile(df["Length"].to_numpy(), 95)) if len(df) > 0 else 0.0

    ul_pkt_size_mean = float(ul["Length"].mean()) if ul_packets > 0 else 0.0
    ul_pkt_size_std  = float(ul["Length"].std(ddof=1)) if ul_packets > 1 else 0.0

    dl_pkt_size_mean = float(dl["Length"].mean()) if dl_packets > 0 else 0.0
    dl_pkt_size_std  = float(dl["Length"].std(ddof=1)) if dl_packets > 1 else 0.0
    dl_pkt_size_p95  = float(np.percentile(dl["Length"].to_numpy(), 95)) if len(dl) > 0 else 0.0

    # IAT 
    iat_mean = float(df["iat"].mean())
    iat_std  = float(df["iat"].std(ddof=1)) if total_packets > 1 else 0.0
    iat_max  = float(df["iat"].max())

    ul_iat_mean = float(ul["iat"].mean()) if ul_packets > 0 else 0.0
    ul_iat_std  = float(ul["iat"].std(ddof=1)) if ul_packets > 1 else 0.0

    dl_iat_mean = float(dl["iat"].mean()) if dl_packets > 0 else 0.0
    dl_iat_std  = float(dl["iat"].std(ddof=1)) if dl_packets > 1 else 0.0

    # Unique destination count
    unique_dst_ips = int(df["Destination"].nunique())

    # throughput
    bytes_per_second = (total_bytes / duration_sec) if duration_sec > 0 else 0.0

    return {
        "client_ip": client_ip,

        # features
        "duration_sec": duration_sec,
        "total_packets": total_packets,
        "ul_packets": ul_packets,
        "dl_packets": dl_packets,
        "ul_bytes": ul_bytes,
        "dl_bytes": dl_bytes,
        "dl_ul_byte_ratio": dl_ul_byte_ratio,
        "dl_ul_packet_ratio": dl_ul_packet_ratio,

        "pkt_size_mean": pkt_size_mean,
        "pkt_size_std": pkt_size_std,
        "pkt_size_p95": pkt_size_p95,

        "ul_pkt_size_mean": ul_pkt_size_mean,
        "ul_pkt_size_std": ul_pkt_size_std,

        "dl_pkt_size_mean": dl_pkt_size_mean,
        "dl_pkt_size_std": dl_pkt_size_std,
        "dl_pkt_size_p95": dl_pkt_size_p95,

        "iat_mean": iat_mean,
        "iat_std": iat_std,
        "iat_max": iat_max,

        "ul_iat_mean": ul_iat_mean,
        "ul_iat_std": ul_iat_std,

        "dl_iat_mean": dl_iat_mean,
        "dl_iat_std": dl_iat_std,

        "unique_dst_ips": unique_dst_ips,
        "bytes_per_second": bytes_per_second,
    }

feature_rows = []
errors = []

for _, row in meta.iterrows():
    fname = row["file"]
    fpath = os.path.join(CSV_FOLDER, fname)
    try:
        df = pd.read_csv(fpath)
        feats = extract_features(df)
        out_row = dict(row)        
        out_row.update(feats)       
        feature_rows.append(out_row)

    except Exception as e:
        errors.append({"file": fname, "error": str(e)})

features_df = pd.DataFrame(feature_rows)

print("Extracted feature rows:", len(features_df))
print("Errors:", len(errors))
if errors:
    display(pd.DataFrame(errors).head(10))

Extracted feature rows: 48
Errors: 0

In [22]:
print(features_df)

                                                file      label  category  \
0                 genai_chatgpt_audio_01_packets.csv      genai       NaN
1                 genai_chatgpt_audio_02_packets.csv      genai       NaN
2                  genai_chatgpt_text_01_packets.csv      genai       NaN
3                  genai_chatgpt_text_02_packets.csv      genai       NaN
4                  genai_chatgpt_text_03_packets.csv      genai       NaN
5                  genai_chatgpt_text_04_packets.csv      genai       NaN
6                  genai_chatgpt_text_05_packets.csv      genai       NaN
7                  genai_chatgpt_text_06_packets.csv      genai       NaN
8                 genai_chatgpt_video_01_packets.csv      genai       NaN
9                 genai_chatgpt_video_02_packets.csv      genai       NaN
10                genai_chatgpt_video_03_packets.csv      genai       NaN
11                genai_chatgpt_video_04_packets.csv      genai       NaN
12                 genai_gemini_audio_01_packets.csv      genai       NaN
13                 genai_gemini_audio_02_packets.csv      genai       NaN
14                 genai_gemini_audio_03_packets.csv      genai       NaN
15                  genai_gemini_text_01_packets.csv      genai       NaN
16                  genai_gemini_text_02_packets.csv      genai       NaN
17                  genai_gemini_text_03_packets.csv      genai       NaN
18                  genai_gemini_text_04_packets.csv      genai       NaN
19                  genai_gemini_text_05_packets.csv      genai       NaN
20                    genai_grok_text_01_packets.csv      genai       NaN
21             genai_perplexity_audio_01_packets.csv      genai       NaN
22              genai_perplexity_text_01_packets.csv      genai       NaN
23          non_genai_browsing_chrome_01_packets.csv  non_genai  browsing
24          non_genai_browsing_chrome_02_packets.csv  non_genai  browsing
25          non_genai_browsing_chrome_03_packets.csv  non_genai  browsing
26          non_genai_browsing_chrome_04_packets.csv  non_genai  browsing
27            non_genai_stream_disney_01_packets.csv  non_genai    stream
28            non_genai_stream_disney_02_packets.csv  non_genai    stream
29            non_genai_stream_disney_03_packets.csv  non_genai    stream
30          non_genai_browsing_google_01_packets.csv  non_genai  browsing
31          non_genai_browsing_google_02_packets.csv  non_genai  browsing
32          non_genai_browsing_google_03_packets.csv  non_genai  browsing
33  non_genai_audio_calling_instagram_01_packets.csv  non_genai   calling
34  non_genai_video_calling_instagram_01_packets.csv  non_genai   calling
35          non_genai_browsing_safari_01_packets.csv  non_genai  browsing
36          non_genai_browsing_safari_02_packets.csv  non_genai  browsing
37          non_genai_browsing_safari_03_packets.csv  non_genai  browsing
38            non_genai_stream_twitch_01_packets.csv  non_genai    stream
39            non_genai_stream_twitch_02_packets.csv  non_genai    stream
40            non_genai_stream_twitch_03_packets.csv  non_genai    stream
41   non_genai_audio_calling_whatsapp_01_packets.csv  non_genai   calling
42   non_genai_video_calling_whatsapp_01_packets.csv  non_genai   calling
43           non_genai_stream_youtube_01_packets.csv  non_genai    stream
44           non_genai_stream_youtube_02_packets.csv  non_genai    stream
45           non_genai_stream_youtube_03_packets.csv  non_genai    stream
46       non_genai_audio_calling_zoom_01_packets.csv  non_genai   calling
47       non_genai_video_calling_zoom_01_packets.csv  non_genai   calling

           app   mode  run_id        client_ip  duration_sec  total_packets  \
0      chatgpt  audio       1   192.168.137.80    332.461600          36057
1      chatgpt  audio       2  192.168.137.109    446.460153          56991
2      chatgpt   text       1   192.168.137.80    423.286492           4637
3      chatgpt   text       2   192.168.137.80    381.932889           7072
4      chatgpt   text       3   192.168.137.80    376.032107           4849
5      chatgpt   text       4  192.168.137.213    268.771202          11088
6      chatgpt   text       5  192.168.137.213    305.928167          30749
7      chatgpt   text       6  192.168.137.109    288.437407           2913
8      chatgpt  video       1   192.168.137.80    255.944020          78632
9      chatgpt  video       2   192.168.137.80    325.386410         102386
10     chatgpt  video       3   192.168.137.80    158.326472          40698
11     chatgpt  video       4  192.168.137.111     61.657081          15207
12      gemini  audio       1  192.168.137.213    315.680091           6714
13      gemini  audio       2  192.168.137.213    347.396879           6415
14      gemini  audio       3  192.168.137.109    353.150368          14508
15      gemini   text       1   192.168.137.80    405.247214           7485
16      gemini   text       2  192.168.137.213    322.604184          57788
17      gemini   text       3  192.168.137.213    126.566072           1171
18      gemini   text       4  192.168.137.213    336.208406           1476
19      gemini   text       5  192.168.137.222    348.986617           6668
20        grok   text       1  192.168.137.222    324.721062          22978
21  perplexity  audio       1  192.168.137.222    240.509812          50424
22  perplexity   text       1  192.168.137.222    323.569554          17913
23      chrome    NaN       1   192.168.137.80    214.936315          81361
24      chrome    NaN       2  192.168.137.222    368.139987         100357
25      chrome    NaN       3  192.168.137.222    233.964255          60188
26      chrome    NaN       4  192.168.137.222    157.568434          29932
27      disney    NaN       1  192.168.137.222    446.669686         434975
28      disney    NaN       2  192.168.137.222    213.233014          34071
29      disney    NaN       3  192.168.137.222    299.542111          22039
30      google    NaN       1  192.168.137.109    355.095066          79275
31      google    NaN       2  192.168.137.222    397.084134          40722
32      google    NaN       3  192.168.137.222    393.225682          49268
33   instagram  audio       1  192.168.137.222    316.868289          19019
34   instagram  video       1  192.168.137.222    344.412188          49212
35      safari    NaN       1  192.168.137.222    333.476984          25671
36      safari    NaN       2  192.168.137.222    288.229293          24614
37      safari    NaN       3  192.168.137.222    283.647012          39454
38      twitch    NaN       1  192.168.137.222    190.904007          40207
39      twitch    NaN       2  192.168.137.222    296.998668          56258
40      twitch    NaN       3  192.168.137.222    252.047400          33125
41    whatsapp  audio       1  192.168.137.109    329.844065           9908
42    whatsapp  video       1  192.168.137.109    330.533506          41143
43     youtube    NaN       1  192.168.137.109    321.939961          38173
44     youtube    NaN       2  192.168.137.222    251.014599          26447
45     youtube    NaN       3  192.168.137.222    271.397880          30686
46        zoom  audio       1  192.168.137.109    375.534506          37833
47        zoom  video       1  192.168.137.109    346.065228          69516

    ul_packets  ...  dl_pkt_size_p95  iat_mean   iat_std    iat_max  \
0        12459  ...           1304.0  0.009220  0.063420   5.943965
1        25072  ...           1242.0  0.007834  0.010069   0.919187
2         1832  ...            964.0  0.091285  0.440281  17.344721
3         2908  ...           1304.0  0.054006  0.265041   8.018130
4         2147  ...           1304.0  0.077548  0.360700   8.132470
5         3472  ...           1304.0  0.024240  0.322431  19.232989
6         5530  ...           1304.0  0.009949  0.121843   6.635843
7         1411  ...           1322.0  0.099017  0.556687  11.212597
8        61315  ...            142.0  0.003255  0.007626   1.676643
9        81559  ...            220.0  0.003178  0.016409   2.956717
10       30538  ...            225.0  0.003890  0.027924   4.995475
11       10722  ...           1242.0  0.004055  0.011229   0.904579
12        1580  ...           1292.0  0.047018  0.940919  55.265769
13        1643  ...           1292.0  0.054154  0.508048   9.359901
14        6616  ...           1444.0  0.024342  0.125201   8.888681
15        2215  ...           1304.0  0.054141  0.487191   9.367021
16        9380  ...           1292.0  0.005583  0.119430  17.690476
17         474  ...           1304.0  0.108084  0.644126   7.778122
18         540  ...           1292.0  0.227783  1.360080  27.299824
19        3048  ...           1444.0  0.052338  0.516425  19.432452
20        9518  ...           1444.0  0.014132  0.116275   4.869552
21       21647  ...           1444.0  0.004770  0.008760   0.676149
22        7540  ...           1444.0  0.018063  0.214372  12.195476
23       28396  ...           1514.0  0.002642  0.055692   7.688236
24       48440  ...           1444.0  0.003668  0.019783   4.184049
25       28524  ...           1444.0  0.003887  0.018312   0.689778
26       14181  ...           1444.0  0.005264  0.024712   1.424018
27       48442  ...           1444.0  0.001027  0.023607   4.138116
28       13253  ...           1444.0  0.006258  0.026714   1.614349
29        9617  ...           1444.0  0.013591  0.102391   5.486958
30       39416  ...           1444.0  0.004479  0.027643   4.691078
31       17079  ...           1444.0  0.009751  0.099246   7.278402
32       23956  ...           1444.0  0.007981  0.059837   7.144138
33        9391  ...           1444.0  0.016661  0.025895   0.746873
34       23812  ...           1179.0  0.006999  0.012872   0.737155
35       12120  ...           1444.0  0.012990  0.140853   7.936130
36        9882  ...           1494.0  0.011710  0.074855   2.162485
37       17285  ...           1444.0  0.007189  0.029033   1.088610
38       17610  ...           1444.0  0.004748  0.012106   0.808185
39       22398  ...           1444.0  0.005279  0.011285   0.800578
40       12558  ...           1444.0  0.007609  0.084730  11.882931
41        5257  ...            718.0  0.033291  0.062466   3.515341
42       18126  ...           1242.0  0.008034  0.017797   1.660657
43        8004  ...           1292.0  0.008434  0.026966   1.618428
44        8281  ...           1292.0  0.009491  0.034478   1.968143
45        7659  ...           1292.0  0.008844  0.032746   4.000120
46       19061  ...            379.0  0.009926  0.023574   1.083487
47       34148  ...           1290.0  0.004978  0.011468   0.969989

    ul_iat_mean  ul_iat_std  dl_iat_mean  dl_iat_std  unique_dst_ips  \
0      0.015748    0.088551     0.005774    0.044403              39
1      0.004693    0.006550     0.010301    0.011554              56
2      0.100521    0.548698     0.085252    0.351864              38
3      0.069919    0.349766     0.042894    0.183274              37
4      0.094811    0.441796     0.063832    0.279323              33
5      0.031596    0.187266     0.020886    0.367889              35
6      0.026849    0.226196     0.006244    0.082504              33
7      0.109284    0.561759     0.089373    0.551894              29
8      0.002116    0.007739     0.007288    0.005585              24
9      0.002777    0.017548     0.004750    0.010711              22
10     0.003094    0.031950     0.006283    0.006899              21
11     0.002730    0.012107     0.007221    0.007934              22
12     0.062723    0.970580     0.042185    0.931644              11
13     0.040621    0.251648     0.058813    0.570193              13
14     0.029221    0.144719     0.020252    0.105944              28
15     0.030830    0.244553     0.063939    0.558284              17
16     0.014224    0.120644     0.003908    0.119123              69
17     0.104643    0.494090     0.110424    0.729067              16
18     0.250350    1.779498     0.214764    1.045102              13
19     0.083999    0.716765     0.025679    0.239175              31
20     0.022336    0.171951     0.008331    0.045742              48
21     0.003626    0.008653     0.005630    0.008741              53
22     0.027803    0.283385     0.010984    0.144471              57
23     0.005299    0.090940     0.001217    0.018025             384
24     0.003590    0.015477     0.003741    0.023088             585
25     0.003522    0.016367     0.004216    0.019898             585
26     0.004711    0.020015     0.005762    0.028273             379
27     0.004894    0.067348     0.000542    0.007522             131
28     0.006986    0.038452     0.005795    0.015039              45
29     0.019895    0.135305     0.008712    0.066131              57
30     0.004401    0.022010     0.004557    0.032259             565
31     0.012997    0.114865     0.007407    0.086148             205
32     0.007281    0.050588     0.008644    0.067427             381
33     0.018246    0.026811     0.015114    0.024873              50
34     0.007066    0.013949     0.006935    0.011774              37
35     0.016685    0.180349     0.009686    0.092040              86
36     0.016736    0.103169     0.008339    0.046843              81
37     0.008184    0.033536     0.006413    0.024938             206
38     0.004679    0.013509     0.004802    0.010889              63
39     0.005375    0.013226     0.005216    0.009791              90
40     0.009748    0.034016     0.006303    0.104172              77
41     0.035623    0.072304     0.030655    0.048900              48
42     0.007934    0.017206     0.008112    0.018248              57
43     0.014845    0.032121     0.006733    0.025151              74
44     0.016210    0.043614     0.006428    0.028873              61
45     0.019479    0.055951     0.005307    0.018377              43
46     0.009495    0.028941     0.010364    0.016407              50
47     0.004498    0.011725     0.005441    0.011195              60

    bytes_per_second
0       8.128550e+04
1       2.322697e+04
2       2.427743e+03
3       1.037250e+04
4       6.246110e+03
5       3.343092e+04
6       1.040071e+05
7       5.580857e+03
8       2.277143e+05
9       2.427789e+05
10      1.758818e+05
11      1.573579e+05
12      1.510247e+04
13      1.306766e+04
14      2.186178e+04
15      1.588306e+04
16      1.928777e+05
17      5.772155e+03
18      2.509577e+03
19      1.194481e+04
20      5.532087e+04
21      9.479559e+04
22      3.941349e+04
23      2.729987e+05
24      1.455334e+05
25      1.329760e+05
26      9.861520e+04
27      1.241723e+06
28      1.414350e+05
29      5.609658e+04
30      1.113298e+05
31      7.018164e+04
32      6.237230e+04
33      2.184489e+04
34      8.164463e+04
35      4.652224e+04
36      6.235062e+04
37      9.258014e+04
38      1.709222e+05
39      1.634237e+05
40      1.158346e+05
41      5.906888e+03
42      8.963859e+04
43      1.031325e+05
44      8.703425e+04
45      1.047174e+05
46      2.317862e+04
47      1.142313e+05

[48 rows x 32 columns]

In [23]:
extraction_path = r"C:\Users\koush\Desktop\GenAi project folder\all_features.csv"
features_df.to_csv(extraction_path, index=False)

In [24]:
import pandas as pd
import numpy as np

df_feat=features_df

print("Shape:", df_feat.shape)
print("Labels:\n", df_feat["label"].value_counts())

Shape: (48, 32)
Labels:
 label
non_genai    25
genai        23
Name: count, dtype: int64

In [25]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:

print("Shape:", df_feat.shape)
print(df_feat["label"].value_counts())
df_feat.head()

Shape: (48, 32)
label
non_genai    25
genai        23
Name: count, dtype: int64

,file,label,category,app,mode,run_id,client_ip,duration_sec,total_packets,ul_packets,...,dl_pkt_size_p95,iat_mean,iat_std,iat_max,ul_iat_mean,ul_iat_std,dl_iat_mean,dl_iat_std,unique_dst_ips,bytes_per_second
0,genai_chatgpt_audio_01_packets.csv,genai,NaN,chatgpt,audio,1,192.168.137.80,332.461600,36057,12459,...,1304.0,0.009220,0.063420,5.943965,0.015748,0.088551,0.005774,0.044403,39,81285.504852
1,genai_chatgpt_audio_02_packets.csv,genai,NaN,chatgpt,audio,2,192.168.137.109,446.460153,56991,25072,...,1242.0,0.007834,0.010069,0.919187,0.004693,0.006550,0.010301,0.011554,56,23226.968701
2,genai_chatgpt_text_01_packets.csv,genai,NaN,chatgpt,text,1,192.168.137.80,423.286492,4637,1832,...,964.0,0.091285,0.440281,17.344721,0.100521,0.548698,0.085252,0.351864,38,2427.743430
3,genai_chatgpt_text_02_packets.csv,genai,NaN,chatgpt,text,2,192.168.137.80,381.932889,7072,2908,...,1304.0,0.054006,0.265041,8.018130,0.069919,0.349766,0.042894,0.183274,37,10372.495048
4,genai_chatgpt_text_03_packets.csv,genai,NaN,chatgpt,text,3,192.168.137.80,376.032107,4849,2147,...,1304.0,0.077548,0.360700,8.132470,0.094811,0.441796,0.063832,0.279323,33,6246.110256

In [ ]:
EXCLUDE = {
    "file",
    "label",
    "client_ip",
    "app",
    "category",
    "mode",
    "run_id",  
}

feature_cols = [
    c for c in df_feat.columns
    if (c not in EXCLUDE) and (df_feat[c].dtype != "O")
]

print("Number of features:", len(feature_cols))
print(feature_cols)

Number of features: 25
['duration_sec', 'total_packets', 'ul_packets', 'dl_packets', 'ul_bytes', 'dl_bytes', 'dl_ul_byte_ratio', 'dl_ul_packet_ratio', 'pkt_size_mean', 'pkt_size_std', 'pkt_size_p95', 'ul_pkt_size_mean', 'ul_pkt_size_std', 'dl_pkt_size_mean', 'dl_pkt_size_std', 'dl_pkt_size_p95', 'iat_mean', 'iat_std', 'iat_max', 'ul_iat_mean', 'ul_iat_std', 'dl_iat_mean', 'dl_iat_std', 'unique_dst_ips', 'bytes_per_second']

In [28]:
X = df_feat[feature_cols].values
y = (df_feat["label"] == "genai").astype(int).values

print("X shape:", X.shape)
print("y distribution:", np.bincount(y))

X shape: (48, 25)
y distribution: [25 23]

In [29]:
pipe_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter=2000))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

lr_scores = cross_val_score(pipe_lr, X, y, cv=cv, scoring="accuracy")

print("LR CV scores:", lr_scores)
print("LR mean:", lr_scores.mean(), "std:", lr_scores.std())

LR CV scores: [0.9        0.9        0.7        0.88888889 0.66666667]
LR mean: 0.8111111111111111 std: 0.10493972402771197

In [30]:
y_pred_lr = cross_val_predict(pipe_lr, X, y, cv=cv)

print("LR Confusion Matrix:\n", confusion_matrix(y, y_pred_lr))
print("\nLR Classification Report:\n")
print(classification_report(y, y_pred_lr, target_names=["non_genai", "genai"]))

LR Confusion Matrix:
 [[21  4]
 [ 5 18]]

LR Classification Report:

              precision    recall  f1-score   support

   non_genai       0.81      0.84      0.82        25
       genai       0.82      0.78      0.80        23

    accuracy                           0.81        48
   macro avg       0.81      0.81      0.81        48
weighted avg       0.81      0.81      0.81        48

In [31]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_scores = cross_val_score(rf, X, y, cv=cv, scoring="accuracy")

print("RF CV scores:", rf_scores)
print("RF mean:", rf_scores.mean(), "std:", rf_scores.std())

RF CV scores: [1.         0.9        0.8        0.88888889 0.77777778]
RF mean: 0.8733333333333334 std: 0.0793803159977411

In [32]:
y_pred_rf = cross_val_predict(rf, X, y, cv=cv)

print("RF Confusion Matrix:\n", confusion_matrix(y, y_pred_rf))
print("\nRF Classification Report:\n")
print(classification_report(y, y_pred_rf, target_names=["non_genai", "genai"]))

RF Confusion Matrix:
 [[24  1]
 [ 5 18]]

RF Classification Report:

              precision    recall  f1-score   support

   non_genai       0.83      0.96      0.89        25
       genai       0.95      0.78      0.86        23

    accuracy                           0.88        48
   macro avg       0.89      0.87      0.87        48
weighted avg       0.88      0.88      0.87        48